### ISSUE TITLE
Get Current Profile does not work with Bearer Auth

### ISSUE THREAD

**Issue by helmut64** [Matthew1471/Enphase-API#7]
I got the entire Bearer auth running with my standalone C++ Mac application which I like to port down to an ESP32 later on for energy switching based on metered data. Thanks for this great documentation.

When requesting the Profile "installer/agf/details.json”, the Bearer token based auth gives error 401. Using an HTTP session cookie e.g.:
”envoy_122143077773=xxx; sessionId=3TUYsfNoGCYPQmCyDPuvoMRAWV6OiNaA"
it works with a different session ID compared to the Bearer login session ID.
It works only if I login via Firefox to envoy.local via login with Enphase, then copying this session ID from the browser into my app.

PS: Have you logged into the Envoy via a TTY serial adapter to see the running code and the JavaScript code (maybe Node.js), or any other trick.

**Comment by helmut64** [comment]
Hi Matthew, thank for the quick answer, cool that you have access to the Envoy, add an additional user account that you can continue to investigate the Envoy after a new SW release.

The username/account is always the same in my test case. The difference is only that the non working session ID I get via the login.json login. The working one I get via the envoy.local login button which goes to:
https://entrez.enphaseenergy.com/authorize?code_challenge=ScInkHS2CAbrLT_O_a0EAQMRyvYOKK9FdJiAljFSRLU&client_id=envoy-ui-client&redirect_uri=https://helmut.dnshome.de/auth/callback&scope=122_ENVOY_SERIAL&response_type=code&code_challenge_method=S256
Yes I have an Enphase installer status and I can install batteries and provision entire sites.
You may know the "Enphase Battery Inside" tour you YT.

My long term goal is to get the Envoy and IQ7/IQ8 to produce power in an island mode, at present the System Controller is not available in Europe. I may need to join the three phases into a single one to have a chance to get this running. For this, understanding profiles is important. Also the PLC communication is probably of help to understand and maybe needed for this.

Best regards, Helmut

**Comment by Matthew1471** [comment]
>My long term goal is to get the Envoy and IQ7/IQ8 to produce power in an island mode, at present the System Controller is not available in Europe. 

I have that with the Tesla Powerwall system (specifically the Tesla Gateway).. The microinverters need to see a grid that is within parameters to continue operating. As the storage battery becomes fully charged the emulated grid can then use frequency-watt to continue providing power to the home but encourage the microinverters to safely reduce (and eventually stop) generating. In the UK at least one has to physically island from the utility to prevent the microinverters trying to power the grid and electrocuting the utility company's workers.

Sunlight Backup (which does not require a battery and was true islandling depending solely on current PV conditions) will not make it to Europe but it doesn't sound like something that would work properly over here anyway (clouds and typically smaller installations due to our smaller homes)

>The difference is only that the non working session ID I get via the login.json login

I am not using `login.json` I use `{Authentication.AUTHENTICATION_HOST}/entrez_tokens`, have you tried the examples at the [wrapper documentation](https://github.com/Matthew1471/Enphase-API/blob/main/Documentation/Wrappers/Python/README.adoc)? I do not like the suggestion in Enphase's official docs to use Enlighten to get the token and prefer to talk to the authentication service once rather than go via Enlighten. The IQ Gateway itself goes via the authentication service and not via Enlighten.

>You may know the "Enphase Battery Inside" tour you YT.
I went to the IQ8 and IQ Battery 5P roadshows in the UK. I'm getting worryingly good at supporting the platform now 🤣 

For 3-phase systems the IQ Gateway I believe can only sit on 1-phase (as you would expect) so one would need to repeat the PLC data on the other phases by purchasing this device the [IQ Relay](https://enphase.com/en-in/download/iq-relay-data-sheet) this behaves as a "built-in phase coupler to distribute power line communications (PLC) signals across phases"
